# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6XaNwJSlGWwo4o7_4wZNpRIAx4Tpej7

1.Write a Python program to calculate the total number of Vowels and Count of each
individual vowel A,E,I,O,U in the string "Guvi Geeks Network Private Limited" ?
"""

def count_vowels(string):
    vowels = 'aeiouAEIOU'
    vowel_count = {}.fromkeys(vowels, 0)
    total_vowels = 0
    for char in string:
        if char in vowel_count:
            vowel_count[char] += 1
            total_vowels += 1
    return total_vowels, vowel_count

string = "Guvi Geeks Network Private Limited"
total_vowels, vowel_count = count_vowels(string)
print("Total number of vowels:", total_vowels)
print("Count of each individual vowel:", vowel_count)

"""2) Create a Pyramid of Numbers from 1 to 20 using For loop?"""

for i in range(1, 21):  # Range from 1 to 20 to create 20 rows
    # Inner loop to print the numbers in each row
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

"""3) Write a program that takes a string and returns a new string with all the vowels
removed.
"""

def remove_vowels(input_string):
    vowels = "aeiouAEIOU"
    new_string = ""
    for char in input_string:
        if char not in vowels:
            new_string += char
    return new_string


input_string = input("Enter a string: ")

print("String without vowels:", remove_vowels(input_string))

"""4) Write a program that takes a string and returns the number of unique characters in it."""

def count_unique_characters(input_string):
    unique_characters = set()
    for char in input_string:
        unique_characters.add(char)
    return len(unique_characters)


input_string = input("Enter a string: ")

print("Number of unique characters:", count_unique_characters(input_string))

"""5.Write a program that takes a string and returns True if it is a palindrome, False otherwise."""

def is_palindrome(input_string):

    input_string = input_string.lower().replace(" ", "")

    return input_string == input_string[::-1]


input_string = input("Enter a string: ")

if is_palindrome(input_string):
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

"""6. Write a program that takes two strings and returns the longest common substring
between them.

"""

def longest_common_substring(str1, str2):
    m = len(str1)
    n = len(str2)


    dp = [[0] * (n + 1) for _ in range(m + 1)]


    max_len = 0

    end_index = 0


    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if str1[i - 1] == str2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1] + 1
                if dp[i][j] > max_len:
                    max_len = dp[i][j]
                    end_index = i - 1


    longest_substring = str1[end_index - max_len + 1: end_index + 1]
    return longest_substring


string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")

result = longest_common_substring(string1, string2)
print("Longest common substring:", result)

"""7) Write a program that takes a string and returns the most frequent character in it.

"""

def most_frequent_character(input_string):
    char_count = {}
    for char in input_string:
        if char in char_count:
            char_count[char] += 1
        else:
            char_count[char] = 1


    max_count = 0
    most_frequent_char = None
    for char, count in char_count.items():
        if count > max_count:
            max_count = count
            most_frequent_char = char

    return most_frequent_char


input_string = input("Enter a string: ")

result = most_frequent_character(input_string)
if result:
    print("Most frequent character:", result)
else:
    print("The string is empty.")

"""8.8) Write a program that takes a string and returns True if it is an anagram of another string,
Falco otherwise
"""

def is_anagram(str1, str2):

    str1 = str1.lower().replace(" ", "")
    str2 = str2.lower().replace(" ", "")


    return sorted(str1) == sorted(str2)

string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")

if is_anagram(string1, string2):
    print("The strings are anagrams.")
else:
    print("The strings are not anagrams.")

"""9.Write the program that takes the string and returns the number of words in it"""

def count_words(input_string):

    words = input_string.split()

    return len(words)

input_string = input("Enter a string: ")


word_count = count_words(input_string)
print("Number of words in the string:", word_count)